Repository Kollektives-Plagiieren/innovative-commercial-market, pull requests merged in 2023-09, with the labels that each got.

#6 Email validation package installed
  server/app/controllers/validation.server.controller.js
  server/package-lock.json
  server/package.json
Labels: enhancement, good first issue, backend

#13 Navigation bar
  client/src/components/Home.js
  client/src/css/Home.css
  client/src/css/NavBar.css
Labels: enhancement, frontend

#19 New login page design
  client/public/img/lake-8231248.jpg
  client/public/index.html
  client/src/components/Home.js
  client/src/components/Login.js
  client/src/css/Home.css
  client/src/css/Login.css
Labels: enhancement, frontend

#21 Fix input label transition
  client/src/components/Login.js
  client/src/css/Login.css
Labels: bug, frontend

#22 Add navbar to login page
  client/src/components/Login.js
  client/src/css/Login.css
Labels: enhancement, frontend

#23 Dev into main
  client/src/components/Login.js
  client/src/css/Login.css
Labels: bug, enhancement, frontend

#26 Design 404 page
  client/src/components/PageNotFound.js
  client/src/css/PageNotFound.css
Labels: enhancement, frontend

#28 Added logout button, improved navbar and login form
  client/src/components/Home.js
  client/src/components/Login.js
  client/src/css/Login.css
Labels: enhancement, frontend

#29 Design signup page and update design of other pages
  client/src/components/Home.js
  client/src/components/Profile.js
  client/src/components/Signup.js
  client/src/css/Login.css
  client/src/css/PageNotFound.css
  client/src/css/Profile.css
  client/src/css/Signup.css
Labels: enhancement, frontend

#30 Dev into main
  client/public/img/rice-field-3490060.jpg
  client/public/img/sunrise-6670717.jpg
  client/src/components/Login.js
  client/src/components/Signup.js
  client/src/css/Login.css
  client/src/css/Signup.css
Labels: enhancement, frontend
